apiVersion: v1
kind: Secret
metadata:
  labels:
     heritage: {{ .Release.Service }}
     release: {{ .Release.Name }}
     chart: {{ template "confluent-operator.chart" . }}
     app: {{ template "confluent-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-apikeys
type: Opaque
data:
  apikeys.json : {{ include "kafka.sasl_users" . | b64enc }}
